export const en = {
    buttonLogOut: "log out",
    headerFriends: "Friends",
    chat:"click to open chat",
    socialMessage: "share something",
    buttonCreatePost: "create post",
    buttonCancel: "Cancel",
    buttonPost: "Post",
    inputComment: "write a comment",
    buttonSend: "send",
    comments: "comments",
    inputFriends: "search users",
    buttonFriends: "search",
    searchUser: "Search Users",
    resultSearch: "Results for: ",
    relationFriend: "friend",
    relationRecive: "send you a friend request",
    relationWatting: "waiting for an answer",
    buttonAdd: "Add",
    buttonAccept: "Accept Request",
    buttonReject: "Accept Reject",
    buttonCopy: "copy",
    inputPost: "what are you thinking about?",
    inputChat: "write a message",
    userConnected: "on line",
    userDesconnected: "off line",
    friendRequest: "no friend requests",
    notFoundUsers: "not found users with that name"
}

export const es = {
    buttonLogOut: "Salir",
    headerFriends: "Amigos",
    chat: "haz clic para abrir el chat",
    socialMessage: "comparte algo",
    buttonCreatePost: "crear publicación",
    buttonCancel: "Cancelar",
    buttonPost: "Publicar",
    inputComment: "escribe un comentario",
    buttonSend: "enviar",
    comments: "comentarios",
    inputFriends: "buscar amigos",
    buttonFriends: "buscar",
    searchUser: "Buscar usuarios",
    resultSearch: "Resultados para: ",
    relationFriend: "amigo",
    relationRecive: "te envió una solicitud de amistad",
    relationWatting: "esperando respuesta",
    buttonAdd: "Añadir",
    buttonAccept: "Aceptar solicitud",
    buttonReject: "Rechazar solicitud",
    buttonCopy: "copiar",
    inputPost: "¿Que estas pensando?",
    inputChat: "escribe un mensaje",
    userConnected: "en linea",
    userDesconnected: "desconectado",
    friendRequest: "no solicitudes de amistad",
    notFoundUsers: "no se encontraron usuario con ese nombre"
};